export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  try {
    const { bookmarks, title = 'Re-Bookmarked 整理结果' } = req.body
    if (!bookmarks) return res.status(400).json({ error: 'Bookmarks data required' })

    const html = generateBookmarkHTML(bookmarks, title)
    
    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    res.setHeader('Content-Disposition', `attachment; filename="bookmarks-organized-${Date.now()}.html"`)
    res.status(200).send(html)
  } catch (error) {
    console.error('Generate HTML error:', error)
    res.status(500).json({ error: 'HTML generation failed', details: error.message })
  }
}

function generateBookmarkHTML(bookmarks, title) {
  const timestamp = new Date().toISOString()
  
  const header = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>${title}</TITLE>
<H1>${title}</H1>
<DL><p>`

  const footer = `</DL><p>
<!-- Generated by Re-Bookmarked on ${timestamp} -->`

  const body = generateBookmarkNodes(bookmarks, 1)
  
  return header + body + footer
}

function generateBookmarkNodes(items, depth) {
  let html = ''
  const indent = '    '.repeat(depth)
  
  for (const item of items) {
    if (item.type === 'folder') {
      html += `${indent}<DT><H3 ADD_DATE="${getTimestamp()}" LAST_MODIFIED="${getTimestamp()}">${escapeHtml(item.title)}</H3>\n`
      if (item.description) {
        html += `${indent}<DD>${escapeHtml(item.description)}\n`
      }
      html += `${indent}<DL><p>\n`
      
      if (item.children && item.children.length > 0) {
        html += generateBookmarkNodes(item.children, depth + 1)
      }
      
      html += `${indent}</DL><p>\n`
    } else if (item.type === 'link') {
      const addDate = getTimestamp()
      const iconAttr = item.icon ? ` ICON="${item.icon}"` : ''
      
      html += `${indent}<DT><A HREF="${escapeHtml(item.url)}" ADD_DATE="${addDate}"${iconAttr}>${escapeHtml(item.title)}</A>\n`
    }
  }
  
  return html
}

function getTimestamp() {
  return Math.floor(Date.now() / 1000)
}

function escapeHtml(text) {
  if (!text) return ''
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
